# Generated by Django 4.0.4 on 2022-05-14 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psg_pharmacy', '0006_alter_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 14, 12, 13, 23, 390125)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 14, 12, 13, 23, 390125)),
        ),
    ]
