# Generated by Django 4.0.4 on 2022-05-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psg_pharmacy', '0010_alter_messages_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.CharField(max_length=100000),
        ),
    ]
