# Generated by Django 4.0.4 on 2022-05-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psg_pharmacy', '0017_messages_current_quantity_messages_demand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='proposed_order_quantity',
            new_name='rol',
        ),
        migrations.AddField(
            model_name='messages',
            name='drug_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
