# Generated by Django 4.0.4 on 2022-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psg_pharmacy', '0018_rename_proposed_order_quantity_messages_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_code', models.CharField(max_length=100)),
                ('drug_name', models.CharField(max_length=200)),
                ('current_quantity', models.FloatField()),
                ('demand', models.FloatField()),
                ('rol', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='messages',
            name='current_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='demand',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='rol',
            field=models.FloatField(),
        ),
    ]
